# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swappity Swap
email: hello@crookedlabs.co
description: "Swappity Swap is a simple tool that lets you swap words or phrases on the web with anything you want"
baseurl: ""
url: "http://swap.crookedlabs.co"
twitter_username: crookedlabs
github_username: CrookedLabs
logo: /assets/images/chrome-slide-440.jpg
fb_appid: "1676433202617672"

# Build settings
markdown: kramdown
